### ISSUE TITLE
Lots of resource warnings

### ISSUE THREAD

**Issue by vancluever** [ooyala/tarball-chef-cookbook#11]
Looks like when a tarball is extracted, there are resource name conflicts (seems to be at least 2 duplicate resources named for each file in the tarball).

Is there possibly a way that this could be re-factored so that these errors go away? I guess they are not causing too many issues, other than being extremely spammy with warnings during a chef-client run, but that may or may not be what happens in the future.

**Comment by kbruner** [comment]
I doubt there's a reasonable way to cut this down significantly.  The cookbook intentionally creates the resources as the tarball is being read, rather than reading in the entire tarball before starting resource creation, to prevent memory management nightmares.  (No one would be happy if it read a 5Gb tarball into memory on an instance with 4Gb of RAM, right?)  And, because of nested resource dependencies (it can't create /foo/bar until it has created the directory /foo, which won't exist at runtime) and to deal with the range of interpretations on how to write a tar file (a lot of the apache.org tarballs don't have explicit entries for directories, even though that seems to be standard),  I don't think there's a way to clean up a lot of the warnings, at least not without trading off more memory usage, slower run-times, and/or more code complexity.

**Comment by vancluever** [comment]
Sorry about not replying earlier, but thanks for the insight. Going to close this now since as mentioned it's not really causing too much grief. If it ever becomes an issue I'll take a look more as well.

Cheers!
