### ISSUE TITLE
undefined method `sensitive' for Chef::Resource::File

### ISSUE THREAD

**Issue by gdardani** [ooyala/tarball-chef-cookbook#6]
Hi, I'm having the following problem on master branch. Is that a bug or I'm doing something wrong? Can you guys take a look please? Please let me know if you need additional information. 

NoMethodError

undefined method `sensitive' for Chef::Resource::File
Cookbook Trace

/var/chef/cache/cookbooks/tarball/providers/x.rb:115:in `block in t_file'

/var/chef/cache/cookbooks/tarball/providers/x.rb:110:in `t_file'

/var/chef/cache/cookbooks/tarball/providers/x.rb:174:in `block in t_extraction'

/var/chef/cache/cookbooks/tarball/providers/x.rb:145:in `t_extraction'

/var/chef/cache/cookbooks/tarball/providers/x.rb:194:in `block in class_from_file'

chef-client -v
Chef: 11.8.2

**Comment by irabinovitch** [comment]
@gdardani  I see you closed the issue. All set? Let us know if we can help.

**Comment by kbruner** [comment]
Looks like the 'sensitive' attribute was added to the file resource in 11.10.  I use it so the contents of every untarred file don't get logged :P  I suppose I could put some kind of conditional based on the client version, but I should probably just note that the minimum chef-client version should be... 11.10.  (I assume there's no technical reason to be running 11.8 instead of 11.10+?)

**Comment by gdardani** [comment]
Thanks for helping guys, worked as expected with Chef: 11.10.4.
